name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps

    - name: Run your tests
      env:
        PARABANK_USERNAME: ${{ secrets.PARABANK_USERNAME }}
        PARABANK_PASSWORD: ${{ secrets.PARABANK_PASSWORD }}
      run: pytest --alluredir=allure-results
    
    - uses: actions/upload-artifact@master
      with:
        name: allure-results
        path: allure-results
        retention-days: 20

    - name: Get Allure history
      uses: actions/checkout@v4.1.1
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@v1.9
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4.0.0
      env:
        PERSONAL_TOKEN: ${{ secrets.PARA_BANK }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
    