---
name: Playwright Tests

on:
  workflow_dispatch:

permissions:
  actions: write
  packages: write
  contents: read

jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        path: ${{ github.sha }}

    - name: Install Python and pip
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip
        python3 -m pip install --upgrade pip

    - name: Install uv
      run: |
        python3 -m pip install uv

    - name: Install dependencies
      run: |
        uv pip install --system -r requirements.txt

    - name: Ensure browsers are installed
      run: uv pip install --system playwright && python3 -m playwright install --with-deps

    - name: Run your tests
      env:
        PARABANK_USERNAME: ${{ secrets.PARABANK_USERNAME }}
        PARABANK_PASSWORD: ${{ secrets.PARABANK_PASSWORD }}
      run: |
        mkdir -p test-results
        python3 -m pytest --alluredir=allure-results --tracing=retain-on-failure

    - name: Upload Playwright traces
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-traces
        path: test-results/
        retention-days: 20

    - uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results
        retention-days: 20

    - name: Get Allure history
      uses: actions/checkout@v4.1.1
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@v1.9
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.PARA_BANK }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
